uploads = []
outputs = []

[[generated]]
id = "UjfP2XNL4n_gQJzS8u2Ob"
uri = "file://public/logos/game-bingo.png"
type = "image"
title = "bingo game card"

[[generated]]
id = "yk5rxRukL1aNe0xVP7kmu"
uri = "file://public/logos/game-dominoes.png"
type = "image"
title = "dominoes game card"

[[generated]]
id = "kXFR1I-DdOtRV6Kn4CUqv"
uri = "file://public/logos/game-pool.png"
type = "image"
title = "pool table game card"

[[generated]]
id = "n035q8_nMSqh1wvJ0_go5"
uri = "file://public/logos/game-darts.png"
type = "image"
title = "darts game card"

[[generated]]
id = "S7gmVeUsHFMFyjVFHcn6-"
uri = "file://public/images/adult-menu-banner.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Eb76qjEV0qFAJ7Bju6Zck"
uri = "file://public/logos/game-horse-racing.png"
type = "image"
title = "generated_image"
